#!/bin/bash                                                                                                                                          
#$ -cwd                                                                                                                                              
#$ -S /bin/bash                                                                                                                                      
#$ -j y                                                                                                                                              

# email address to send notices to                                                                                                                   
#$ -M nedelec@math.stanford.edu                                                                                                                      
#$-m bea                                                                                                                                             

## set a name to make it easy to pick out of qstat output                                                                   #$ -N finrun                                                                                                                                         

        module load plink

##  plink --bfile ~/NFG/raw/NFBC/Mat/NFBC_dbGaP_20091127 --noweb --cluster --matrix                                                                    
## Clean genotype data using criteria that p-val for HWE < 0.0001,                                                                                   
## MAF > 0.01 and                                                                                                                                    
## call rate > 95%                                                                                                                                   

##plink --noweb --from-kb 65000 --to-kb 83000 --chr 4 --bfile ~/NFG/raw/NFBC/Mat/NFBC_dbGaP_20091127  --maf 0.01 --hwe 0.0001 --geno 0.05 --make-bed --out ~/NFG/raw/Hd4cl
##plink --noweb --from-kb 40000 --to-kb 60000 --chr 19 --bfile ~/NFG/raw/NFBC/Mat/NFBC_dbGaP_20091127   --maf 0.01 --hwe 0.0001 --geno 0.05 --make-bed  --out ~/NFG/raw/Hd19cl 
##plink --noweb --from-kb 47000 --to-kb 63000 --chr 1 --bfile ~/NFG/raw/NFBC/Mat/NFBC_dbGaP_20091127 --maf 0.01 --hwe 0.0001 --geno 0.05 --make-bed  --out ~/NFG/raw/Hd1cl  


## Additional step to filter out copy number variants                                                                                                
##plink --noweb --bfile ~/NFG/raw/Hd19cl --write-snplist --out ~/NFG/raw/Hd19cl
##grep "cnv" ~/NFG/raw/Hd19cl.snplist > cnvs.txt
##plink --noweb --bfile ~/NFG/raw/Hd19cl --exclude cnvs.txt --make-bed  --out ~/NFG/raw/Hd19cl
##plink --noweb --bfile ~/NFG/raw/Hd19cl --recodeA --out ~/NFG/raw/Hd19clA

##plink --noweb --bfile ~/NFG/raw/Hd4cl --write-snplist --out ~/NFG/raw/Hd4cl
##grep "cnv" ~/NFG/raw/Hd4cl.snplist > cnvs.txt
##plink --noweb --bfile ~/NFG/raw/Hd4cl --exclude cnvs.txt --make-bed  --out ~/NFG/raw/Hd4cl
##plink --noweb --bfile ~/NFG/raw/Hd4cl --recodeA	 --out ~/NFG/raw/Hd4clA

##plink --noweb --bfile ~/NFG/raw/Hd1cl --write-snplist --out ~/NFG/raw/Hd1cl
##grep "cnv" ~/NFG/raw/Hd1cl.snplist > cnvs.txt
##plink --noweb --bfile ~/NFG/raw/Hd1cl --exclude cnvs.txt --make-bed  --out ~/NFG/raw/Hd1cl
##plink --noweb --bfile ~/NFG/raw/Hd1cl --recodeA	 --out ~/NFG/raw/Hd1clA

##For heritability  full size SNP
## plink --noweb  --bfile ~/NFG/raw/NFBC/Mat/NFBC_dbGaP_20091127 --maf 0.01 --hwe 0.0001 --geno 0.05 --make-bed  --out ~/NFG/raw/allgene
## plink --noweb --bfile ~/NFG/raw/allgene --write-snplist --out ~/NFG/raw/allgene
## plink --noweb --bfile ~/NFG/raw/allgene --recodeA  --out ~/NFG/raw/allgeneA



## plink --bfile  ~/NFG/raw/NFBC/Mat/NFBC_dbGaP_20091127 --maf 0.01 --hwe 0.0001 --geno 0.05 --noweb  --recode12 --output-missing-genotype 0 --transpose --out ~/NFG/raw/NFBC_transpose




## clean pheno in R module load R put them in the same order as tfam
## library(plyr)
## testpheno= read.table('~/NFG/raw/pheno2', header=T, sep='')
## pheno<-testpheno[,c(-3,-4,-5,-6,-7,-8)]
## tfam<-read.table("~/NFG/raw/NFBC_transpose.tfam")
## names(tfam)<-c("SUBJID","x","y","t","z","w") 
## opheno<-join(tfam[,c(1,2)],pheno[,c(2,3,4,5,6)],"SUBJID")
## Hpheno<-data.matrix(opheno[,c(1,2,3)])
## write.table(Hpheno,file="~/NFG/raw/Hpheno",row.names=F,col.names=F)
## Lpheno<-data.matrix(opheno[,c(1,2,4)])
## write.table(Lpheno,file="~/NFG/raw/Lpheno",row.names=F,col.names=F)
## Tpheno<-data.matrix(opheno[,c(1,2,5)])
## write.table(Tpheno,file="~/NFG/raw/Tpheno",row.names=F,col.names=F)


## Create BN matrix (Balding-Nichols) = marker-based kinship matrix
## ~/NFG/emmax/emmax-kin -v -h  -d 10  ~/NFG/raw/NFBC_transpose
## will generate [tped_prefix].hBN.kinf

##Create IBS matrix
## ~/NFG/emmax/emmax-kin -v -h -s -d 10 ~/NFG/raw/NFBC_transpose 
## will generate [tped_prefix].hIBS.kinf)

## Use EMMAX to compute heritability
## ~/NFG/emmax/emmax -v -d 10 -t ~/NFG/raw/NFBC_transpose -p ~/NFG/raw/Hpheno -k ~/NFG/raw/NFBC_transpose.hBN.kinf -o ~/NFG/result/H_emmaxnb


## ~/NFG/emmax/emmax -v -d 10 -t ~/NFG/raw/NFBC_transpose -p ~/NFG/raw/Hpheno -k ~/NFG/raw/NFBC_transpose.hIBS.kinf -o ~/NFG/result/H_emmaxibs

##~/NFG/emmax/emmax -v -d 10 -t ~/NFG/raw/NFBC_transpose -p ~/NFG/raw/Lpheno -k ~/NFG/raw/NFBC_transpose.hBN.kinf -o ~/NFG/result/L_emmaxnb





##~/NFG/emmax/emmax -v -d 10 -t ~/NFG/raw/NFBC_transpose -p ~/NFG/raw/Lpheno -k ~/NFG/raw/NFBC_transpose.hIBS.kinf -o ~/NFG/result/L_emmaxibs



 ~/NFG/emmax/emmax -v -d 10 -t ~/NFG/raw/NFBC_transpose -p ~/NFG/raw/Tpheno -k ~/NFG/raw/NFBC_transpose.hBN.kinf -o ~/NFG/result/T_emmaxnb


##-27850.31381                                                                                                     ##-27863.0367                                                                                                      ##1.711555051                                                                                                      ##800.5117527                                                                                                      ##1370.119934                                                                                                      ##0.2266277306                                                                                                      



~/NFG/emmax/emmax -v -d 10 -t ~/NFG/raw/NFBC_transpose -p ~/NFG/raw/Tpheno -k ~/NFG/raw/NFBC_transpose.hIBS.kinf -o ~/NFG/result/T_emmaxibs

## Estimated time
## CPU              = 10:58:40
## Max vmem         = 2.315G

